### ISSUE TITLE
Select Templating Engine

### ISSUE THREAD

**Issue by Talha5** [emerald-rubies/tenacious#13]
Which template Engine we should use here?

- Haml

- Erb

- Slim

**Comment by Exellin** [comment]
My vote is for erb.  I've never felt compelled to switch since I can easily understand what is happening in a erb document and typing an element then pressing tab in visual studio code creates the markup for me.  If one of you can write a compelling reason I could be convinced to try one of the others.

**Comment by pachonk** [comment]
@Exellin I'm convinced that over time, I can get you to see why slim can be super fast and powerful and clean.
Now isn't the time, but after our whole team knows erb and understands views and controllers and such, we can try a few views slim or even haml and you can see what makes them so powerful, imho.

**Comment by troystarwalt** [comment]
Seems reasonable to start with ERB and switch to HAML/Slim.
