### ISSUE TITLE
As a user, I want to be able to add an inventory and associate it with myself or any of my organizations

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#79]
Inventory.owner_id and Inventory.owner_type = [:user, :organization] which is therefor a "polymorphic" rails association could be an option.

**Comment by Exellin** [comment]
I'm working on this right now

**Comment by Exellin** [comment]
I assume this is only organizations you own, right?  You shouldn't be able to add any inventory to any organization you are just a part of.

**Comment by pachonk** [comment]
I don't know, it could make sense someday to have either/or based on a flag.

**Comment by Exellin** [comment]
o.k. I'll keep it as just owner for now.  Perhaps in the future we can put in a organization level like for inventories (read, write, admin).  If you have admin access you can create an inventory and associate it to the organization.

**Comment by Exellin** [comment]
I tried to make an array with the current user and the owned inventories of the user for the owner of the inventory but wasn't able to get it to work.  Is that possible?

For the time being I am falling back to nested routes to grab the owner from the url.

**Comment by pachonk** [comment]
You might need to make user.all_inventories that merges org invs and user.inventories (or something similar)

**Comment by Exellin** [comment]
Don't think you understand my question.  User.inventories will already grab all inventories it owns (and is part of since we will add the user to inventory.users on create).

My issue is assigning an inventory an owner either through the form or on create.

Do we want to nest the inventories in this project?  For example if a user creates an inventory do we want it to live in /users/user_id/inventories/inventory_id.  Or just /inventories/inventory_id.  This is how Github works with repositories with either /organization or /user and I think it makes sense.

If that is the case, you can ignore my question since I was trying to get the owner functionality working in the /inventories/new route and wasn't sure how to pass in the owner in the form.
